

<table class="home_footer"  cellspacing="0"  >
<tr>

<td class="top"> 
<font class="gold">A special and personalised gift</font>
<p class="small">TheoryMine offers a range of different gift packages to suit everyone! <br/>
You will be able to name a theorem, publish it in our journal, purchase a gift package, and even have your theorem printed on a t-shirt, mug, or mouse-mat!  
</p>
</td>

<!--<center><a class="img_link" href="products.html"><img src="images/gift_button.jpg" width="100px"></a> -->

<td width="1px" bgcolor="white">
</td>



<td class="top">
<font class="gold">The latest discovered theorems</font>

<p class="small" style="font:3px">
<?
$res = get_all_points_in_type('thm.named', 0, 5);
if($res['rowcount'] == 0) {
  ?><div class="short-theorem-list-title">Be the first the name a theorem!</div><?
} else {
  ?>
  <ul class="short-theorem-list"><?
  foreach($res['rows'] as $row) {
    ?><li>
    <a href="?go=theorem&pid=<? print $row['id']; ?>">
    <? print htmlentities($row['title']); ?></a><span class="date">
    [<? print sqltimestamp_to_str($row['time_stamp']); ?>]</span> 
    </li><?
  }

  
}
?>
</p>
</td>

<td width="1px" bgcolor="white">
</td>

<td class="top"><font class="gold">Pythagoras, Kepler, Einstein...<br> you could be the next!</font>
<p class="small">
TheoryMine offers personalised, newly discovered, mathematical theorems! <br/> By naming your very own mathematical theorem, newly generated by one of the world's most advanced computerised theorem provers, you can immortalise your loved ones, teachers, friends and even yourself and your favourite pets. 
</p>
</td>

</tr>

<tr>

<td class="bottom">
<center><a class="products_button" href="?go=products" > gift packages</a>
</center>
</td>

<td width="1px" bgcolor="white">
</td>

<td class="bottom">
<center>


</ul><div class="more-theorems"><?
  if($res['more']){
  	  
    ?><center><a class="products_button" href="?go=theorems"> see more...</a>
   </center><?
  }
  
  ?> </div>


</center>
</td>

<td width="1px" bgcolor="white">
</td>

<td class="bottom">
<center><a class="buynow_button" href="?go=discover">name a theorem</a>
</center>
</td>

</tr>



</table>




