<?
$here_link = "?go=overview";
$header_title = "Home";
include 'pages/common_parts/header.php';


$viewed_theorems= $_REQUEST['viewed_theorems'];
$this_limit= 15; 
//print "fristr" . $viewed_theorems . "<br>"; 
//print "second" .$this_limit  . "<br>"; ;
$theorems=get_all_points_in_type('thm.named', $viewed_theorems, $this_limit );

?>


<div class="main_buttons" id="main_buttons" >

<div class="about" align="center" style = "text-align:center;   margin-left:auto; margin-right: auto; width: 680px;">
  <font class="gold">
  Welcome to TheoryMIne! <br/>
  <br/>
  </font>
  <!--TheoryMine lets you name a personalised, newly discovered, mathematical theorems as a novelty gift.-->
  <b><?print $thislang['overview_title'];?></b>
</div>
  

<? // not logged in 
if(!isset($_SESSION['id'])) {
?>

  
  <table style="float:left;width:30%; ">
  <tr>
  <td style="width:30%; text-align:center;">
  <font size="3pt" color="#666666">
  <i>"During my time as an eager undergraduate mathematician, I'd often wonder what it would feel like to prove a truly new result ... but Aron's theorem is now a reality, and I've got the certificate to prove it."</i> </font><br/>
  <font style="font-size:small;font-style:italic; text-align:right;">
  <font color = "#b4975a"> Jacob Aron </font>,
  <a href="http://www.newscientist.com/article/dn19809-you-too-can-get-that-pythagoras-feeling"> The New Scientist </a> </font>
  <br/><br/>
  </td>
  </tr>
  <tr ">
  <td style="width:30%; text-align:center;">
  <!--
   <a href="?go=testimonials"><img src="images/anne-glover_home.<?print   $thislang['lang'];?>.jpeg" width="200px"></a> -->
   <font size="3pt" color="#666666"><i>
   "Pythagoras spent his life proving his, and Fermat died still trying, but for the would-be genius today, a mathematical theorem is only a mouse-click away."
   </i> </font><br/>
     <font style="font-size:small;font-style:italic; text-align:right;">
  <font color = "#b4975a"> Chris Watt </font>,
   <a href="http://www.heraldscotland.com/news/education/your-own-maths-theorem-for-15-1.1068654"> The Herald </a> </font>
   
  
  </td>
  </tr>
  </table>
  
  <div class="about" align="center" style = "text-align:center;   margin-left:auto; margin-right: auto; width: 680px;">
    <font class="tagline">
  <!--You can name your very own mathematical theorem, newly generated by one of the world's most advanced computerised theorem provers (a kind of robot mathematician), and
  you can immortalise your loved ones, teachers, friends and even yourself and your favourite pets. -->
  <?print $thislang['overview_tagline'];?>
  </font> 
  <br/><br/>
  
  <a href="?go=certificate_example"><!--See an example theorem certificate-->
  <?print $thislang['overview_see_example'];?>
  </a>
  </div>
  
  <!--
  <div  align="left" style = "text-align:left;  margin-top: 20px; margin-left:20px; width: 600px; font: 6px; ">
  <i>"During my time as an eager undergraduate mathematician, I'd often wonder what it would feel like to prove a truly new result and have my name immortalised in the mathematical history books. I thought that dream had died when I gave up maths to become a science writer, but Aron's theorem is now a reality, and I've got the certificate to prove it."</i>
  </div>
  -->
  
 <div class="preview" style = "text-align:center;   margin-left:auto; margin-right: auto; width: 35%;">
  <font style="font-weight: bold; color:#B4975A; font-size:18pt;"> <i><!--Get Started:--><?print $thislang['overview_get_started'];?>  </i></font><!--Choose your Theorem Name--><?print $thislang['overview_choose'];?> <? include("pages/common_parts/question-mark.php"); ?>
  
     <form action="?go=discover" method="post"> 
            <input class="field" type="text" name="tname" maxlength="40" size="40"> 
          <br />
            <input class="button" type="submit" value="<?print $thislang['overview_preview'];?>" >  
     </form>
     
   <div style="text-align: center;">
        <?print $thislang['overview_eg'];?><!--e.g. Tom's theorem, or The Bucklesham lemma-->
     </div>
  </div> 

<table class="three_steps" style="width: 100%;">
<tr>
<td> 
<div class="one_of_three_steps">
<a href="?go=discover" onMouseOver="mouseover(1)" onMouseOut="mouseout()"><span class="number_button2">1</span>
<font class="gold"><?print $thislang['overview_you'];?></font> <!--choose a name--><?print $thislang['overview_you2'];?></a>
</div>
</td>

<td>
<div class="one_of_three_steps">
<a href="?go=faq" onMouseOver="mouseover(3)" onMouseOut="mouseout()"><span class="number_button2">2</span>
<font class="gold"><?print $thislang['overview_we'];?></font> <!--discover a theorem--><?print $thislang['overview_we2'];?></a> 
</div>
</td>

<td>
<div class="one_of_three_steps">
<a href="?go=products" onMouseOver="mouseover(2)" onMouseOut="mouseout()"><span class="number_button2">3</span>
<font class="gold"><?print $thislang['overview_they'];?></font> <!--get a great gift--><?print $thislang['overview_they2'];?></a>
</div>
</td>

</tr>

</table>

<table style="margin-top: 20px; " >
<tr>
<td style=" border: 2px solid #d7d7d7;background-color: #f3efe5; width: 25%; padding: 5px; vertical-align: top;"> 
<font class="gold">Many Ideas for a special and personalized gift.</font>

<p class="small" >TheoryMine offers a range of different gift packages to satisfy evevryone! <br/>You can name a theorem and have it printed on a t-shirt, mug, or mouse-mat!  
</p><br>
<!--<center><a class="img_link" href="products.html"><img src="images/gift_button.jpg" width="100px"></a> -->
<center> 
<a href="?go=products#gift_items"><img src="images/gadgets.png" width="310px"</a>
</center>
</td>

<td style=" border: 2px solid #d7d7d7;background-color: #f3efe5; width: 25%; padding: 5px; vertical-align: top;">
<font class="gold">Latest named Theorems:</font>
<p class="small">

</p>

<?
if($theorems['rowcount'] == 0) {
  ?>
  <div class="short-theorem-list-title">Be the first the name a theorem!</div><?
} 
else {
  ?>
  <ul  class="short-theorem-list">
    <? foreach($theorems['rows'] as $row) {
      ?>
      <li>
      <a href="?go=theorem&pid=<? print $row['id']; ?>"><? print htmlentities($row['title']); ?>
      </a><span class="date"> [<? print sqltimestamp_to_str($row['time_stamp']); ?>]</span> 
    </li><?
    }?>
    </ul>
    
  <div class="more-theorems"><?
  
   if ($viewed_theorems  >=  $this_limit){
   $viewed_theorems2 = $viewed_theorems - $this_limit;
    ?><a href="?go=theorems&viewed_theorems=<? print $viewed_theorems2 ; ?>"> Previous</a><?
  }
  
  if (($viewed_theorems  >=  $this_limit) && ($theorems['more'])){?>
  	  |
  <?}
  
  if($theorems['more']){

    $viewed_theorems2 = $viewed_theorems + $this_limit;
    ?> <a href="?go=theorems&viewed_theorems=<? print $viewed_theorems2 ; ?>"> Next </a><? 
  } ?>
  
  </div>
<?    
}
?>

</td>


<td style=" border: 2px solid #d7d7d7;background-color: #f3efe5; width: 25%; padding: 5px; vertical-align: top;">
<font class="gold">Send Us Your Feedback!</font>
<form action="?go=send_mail">
<table method="post" style="margin:10px 0 0 5px;">
<tr>
<td>Email Adress:</td>
<td>
<input type="text" name="email_address" value="" maxlength="100" />
</td>
</tr>
<tr>
<td>Comments:</td>
<td>
<textarea rows="10" cols="30" name="comments"></textarea>
</td>
</tr>
<tr><td>&nbsp;</td>
<td>
<input class="button"  type="submit" value="Submit" >
</td>
</tr>
</table>
</form>


</td>
</tr>
</table>




<!--
<div class="mascots" >
  <img src="images/mathematicians2.png" align="middle"style="width:50%;"> ... you could be next! 
</div>
-->




<? } // logged in 

else {
?>

  <? include("pages/common_parts/discoveries-in-progress.php"); ?>

  <? include("pages/common_parts/discovered-theorems.php"); ?>
  
  <div class="clear"></div>
  <?
}


?>







<?
 
/*include("pages/common_parts/new_theorems.php");*/ 
 
?>
</p>
